---
# handlers file for deploy-yii2-php-app

- name: restart nginx
  service:
    name: nginx
    state: reloaded
      
- name: deploy application
  shell: docker stack deploy -c /home/ec2-user/docker-compose.yml yii2app